/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ms.ais.weather.app;

import ms.ais.weather.list.LinkedList;

import static ms.ais.weather.utilities.StringUtils.join;
import static ms.ais.weather.utilities.StringUtils.split;
import static ms.ais.weather.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
